from sqlalchemy import DECIMAL as Decimal
import datetime

data = {
    "USTAN": {
        "ustan.cycles": [
            {
                "chi": 1005549224, 
                "regime_id": 1, 
                "intention_id": 1, 
                "cycle_id": 1, 
                "drug_names": "CARBO&PACLI WKLY", 
                "diagnosis": "Breast Cancer", 
                "init_appointment_date": datetime.datetime(2018, 9, 13, 0, 0), 
                "elapsed_days": 0, 
                "interval_days": 20, 
                "appointment_date": datetime.datetime(2018, 9, 13, 0, 0), 
                "intention": "Neo-Adjuvant", 
                "regime": "PACLITAX WKLY", 
                "cycle": 1, 
                "p_ps": -1, 
                "ps": 2, 
                "nausea": 3, 
                "vomiting": 0, 
                "diarrhoea": 2, 
                "constipation": 1, 
                "oralMucositis": 0, 
                "oesophagitis": 4, 
                "neurotoxicity": 4, 
                "handFoot": 3, 
                "skin": 3, 
                "hypersensitivity": 4, 
                "fatigue": 5, 
                "required_doses": Decimal("3649.935470")
            }, 
            {
                "chi": 1005549224, 
                "regime_id": 130, 
                "intention_id": 88, 
                "cycle_id": 1124, 
                "drug_names": "BEP 5 DAY MET", 
                "diagnosis": "Breast Cancer", 
                "init_appointment_date": datetime.datetime(2018, 3, 22, 0, 0), 
                "elapsed_days": 84, 
                "interval_days": 20, 
                "appointment_date": datetime.datetime(2018, 6, 14, 0, 0), 
                "intention": "Neo-Adjuvant", 
                "regime": "FEC-D NEO (FEC)", 
                "cycle": 5, 
                "p_ps": -1, 
                "ps": 1, 
                "nausea": 1, 
                "vomiting": 4, 
                "diarrhoea": 4, 
                "constipation": 6, 
                "oralMucositis": 0, 
                "oesophagitis": 1, 
                "neurotoxicity": 5, 
                "handFoot": 3, 
                "skin": 2, 
                "hypersensitivity": 5, 
                "fatigue": 5, 
                "required_doses": Decimal("1685.106444")
            }, 
            {
                "chi": 1005549224, 
                "regime_id": 884, 
                "intention_id": 523, 
                "cycle_id": 7336, 
                "drug_names": "BEP 5 DAY MET", 
                "diagnosis": "Breast Cancer", 
                "init_appointment_date": datetime.datetime(2020, 5, 30, 0, 0), 
                "elapsed_days": 21, 
                "interval_days": 20,
                "appointment_date": datetime.datetime(2020, 6, 20, 0, 0), 
                "intention": "Neo-Adjuvant", 
                "regime": "FEC-D (FEC)", 
                "cycle": 2, 
                "p_ps": -1, 
                "ps": 1, 
                "nausea": 1, 
                "vomiting": 0, 
                "diarrhoea": 3, 
                "constipation": 2, 
                "oralMucositis": 1, 
                "oesophagitis": 5, 
                "neurotoxicity": 5, 
                "handFoot": 5, 
                "skin": 1, 
                "hypersensitivity": 4, 
                "fatigue": 5, 
                "required_doses": Decimal("1893.169694")
            }, 
            {
                "chi": 1005549224, 
                "regime_id": 1644, 
                "intention_id": 982, 
                "cycle_id": 13762, 
                "drug_names": "BEP 5 DAY MET", 
                "diagnosis": "Breast Cancer", 
                "init_appointment_date": datetime.datetime(2020, 6, 13, 0, 0), 
                "elapsed_days": 63, 
                "interval_days": 19, 
                "appointment_date": datetime.datetime(2020, 8, 15, 0, 0), 
                "intention": "Neo-Adjuvant", 
                "regime": "FEC-D (D)", 
                "cycle": 4, 
                "p_ps": -1, 
                "ps": 1, 
                "nausea": 1, 
                "vomiting": 0, 
                "diarrhoea": 4, 
                "constipation": 6, 
                "oralMucositis": 1, 
                "oesophagitis": 4, 
                "neurotoxicity": 4, 
                "handFoot": 2, 
                "skin": 1, 
                "hypersensitivity": 5, 
                "fatigue": 3, 
                "required_doses": Decimal("2266.419613")
            }, 
            {
                "chi": 1005549224, 
                "regime_id": 1797, 
                "intention_id": 1064, 
                "cycle_id": 15217, 
                "drug_names": "CARBO&PACLI WKLY", 
                "diagnosis": "Breast Cancer", 
                "init_appointment_date": datetime.datetime(2018, 2, 25, 0, 0),
                "elapsed_days": 189, 
                "interval_days": 18, 
                "appointment_date": datetime.datetime(2018, 9, 2, 0, 0), 
                "intention": "Neo-Adjuvant", 
                "regime": "FEC-D NEO (FEC)", 
                "cycle": 10, 
                "p_ps": -1, 
                "ps": 3, 
                "nausea": 2, 
                "vomiting": 3, 
                "diarrhoea": 5, 
                "constipation": 3, 
                "oralMucositis": 1, 
                "oesophagitis": 1, 
                "neurotoxicity": 2, 
                "handFoot": 2, 
                "skin": 1, 
                "hypersensitivity": 2, 
                "fatigue": 5, 
                "required_doses": Decimal("3925.381275")
            }, 
            {
                "chi": 1005549224, 
                "regime_id": 1834, 
                "intention_id": 1087, 
                "cycle_id": 15490, 
                "drug_names": "BEP 5 DAY MET", 
                "diagnosis": "Breast Cancer", 
                "init_appointment_date": datetime.datetime(2018, 12, 9, 0, 0), 
                "elapsed_days": 126, 
                "interval_days": 18, 
                "appointment_date": datetime.datetime(2019, 4, 14, 0, 0), 
                "intention": "Neo-Adjuvant", 
                "regime": "FEC-D NEO (FEC)", 
                "cycle": 7, 
                "p_ps": -1, 
                "ps": 3,
                "nausea": 2,
                "vomiting": 2,
                "diarrhoea": 2,
                "constipation": 4,
                "oralMucositis": 3,
                "oesophagitis": 6,
                "neurotoxicity": 5,
                "handFoot": 2,
                "skin": 6,
                "hypersensitivity": 1,
                "fatigue": 5,
                "required_doses": Decimal("4852.662828")}, {"chi": 1005549224,
                "regime_id": 1888,
                "intention_id": 1110,
                "cycle_id": 15878,
                "drug_names": "CARBO&PACLI WKLY",
                "diagnosis": "Breast Cancer",
                "init_appointment_date": datetime.datetime(2020, 1, 2, 0, 0),
                "elapsed_days": 84,
                "interval_days": 21,
                "appointment_date":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        datetime.datetime(2020, 3, 26, 0, 0),
                "intention": "Neo-Adjuvant",
                "regime": "PACLITAX",
                "cycle": 5,
                "p_ps": -1,
                "ps": 1,
                "nausea": 1,
                "vomiting": 2,
                "diarrhoea": 3,
                "constipation":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1,
                "oralMucositis": 1,
                "oesophagitis": 6,
                "neurotoxicity": 6,
                "handFoot": 4,
                "skin": 2,
                "hypersensitivity": 4,
                "fatigue": 5,
                "required_doses": Decimal("4882.554832")}, {"chi": 1005549224,
                "regime_id": 1939,
                "intention_id": 1142,
                "cycle_id": 16393,
                "drug_names": "BEP 5 DAY MET",
                "diagnosis": "Breast Cancer",
                "init_appointment_date": datetime.datetime(2020, 10, 21, 0, 0),
                "elapsed_days": 105,
                "interval_days": 15,
                "appointment_date": datetime.datetime(2021, 2, 3, 0, 0),
                "intention": "Neo-Adjuvant",
                "regime": "PACLITAX",
                "cycle": 6,
                "p_ps": -1,
                "ps": 1,
                "nausea": 2,
                "vomiting": 4,
                "diarrhoea": 5,
                "constipation": 3,
                "oralMucositis": 1,
                "oesophagitis": 6,
                "neurotoxicity": 1,
                "handFoot": 4,
                "skin": 1,
                "hypersensitivity": 3,
                "fatigue": 6,
                "required_doses": Decimal("959.901679")}, {"chi": 1005549224,
                "regime_id": 2172,
                "intention_id": 1294,
                "cycle_id": 18326,
                "drug_names": "CARBO&PACLI WKLY",
                "diagnosis":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "Breast Cancer",
                "init_appointment_date": datetime.datetime(2018, 11, 26, 0, 0),
                "elapsed_days": 147,
                "interval_days": 18,
                "appointment_date": datetime.datetime(2019, 4, 22, 0, 0),
                "intention": "Neo-Adjuvant",
                "regime": "VINORELBINE IV 1",
                "cycle": 8,
                "p_ps": -1,
                "ps": 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "nausea": 3,
                "vomiting": 3,
                "diarrhoea": 5,
                "constipation": 6,
                "oralMucositis": 0,
                "oesophagitis": 3,
                "neurotoxicity": 1,
                "handFoot": 6,
                "skin": 6,
                "hypersensitivity": 5,
                "fatigue":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        2,
                "required_doses": Decimal("635.512842")}, {"chi": 1005549224,
                "regime_id": 2349,
                "intention_id": 1396,
                "cycle_id": 19636,
                "drug_names": "BEP 5 DAY MET",
                "diagnosis": "Breast Cancer",
                "init_appointment_date": datetime.datetime(2020, 10, 3, 0, 0),
                "elapsed_days": 0,
                "interval_days": 16,
                "appointment_date": datetime.datetime(2020, 10, 3, 0, 0),
                "intention": "Neo-Adjuvant",
                "regime": "FEC-D NEO (FEC)",
                "cycle": 1,
                "p_ps": -1,
                "ps": 2,
                "nausea": 1,
                "vomiting": 1,
                "diarrhoea": 4,
                "constipation": 6,
                "oralMucositis": 0,
                "oesophagitis": 4,
                "neurotoxicity": 1,
                "handFoot": 5,
                "skin": 1,
                "hypersensitivity": 5,
                "fatigue": 4,
                "required_doses": Decimal("1339.955771")}, {"chi": 1005549224,
                "regime_id": 2457,
                "intention_id": 1456,
                "cycle_id": 20702,
                "drug_names": "CARBO&PACLI WKLY",
                "diagnosis": "Breast Cancer",
                "init_appointment_date": datetime.datetime(2019, 6, 20, 0, 0),
                "elapsed_days": 147,
                "interval_days": 17,
                "appointment_date": datetime.datetime(2019, 11, 14, 0, 0),
                "intention": "Neo-Adjuvant",
                "regime": "PACLITAX",
                "cycle": 8,
                "p_ps": -1,
                "ps": 3,
                "nausea": 0,
                "vomiting": 0,
                "diarrhoea": 6,
                "constipation": 1,
                "oralMucositis": 1,
                "oesophagitis": 6,
                "neurotoxicity": 4,
                "handFoot": 6,
                "skin": 3,
                "hypersensitivity": 1,
                "fatigue": 6,
                "required_doses": Decimal("1310.123773")}, {"chi": 1005549224,
                "regime_id": 2564,
                "intention_id": 1512,
                "cycle_id": 21555,
                "drug_names": "CARBO&PACLI WKLY",
                "diagnosis": "Breast Cancer",
                "init_appointment_date": datetime.datetime(2019, 7, 14, 0, 0),
                "elapsed_days": 126,
                "interval_days": 20,
                "appointment_date": datetime.datetime(2019, 11, 17, 0, 0),
                "intention": "Neo-Adjuvant",
                "regime": "PACLITAX",
                "cycle": 7,
                "p_ps": -1,
                "ps": 2,
                "nausea": 2,
                "vomiting": 0,
                "diarrhoea": 3,
                "constipation": 1,
                "oralMucositis": 2,
                "oesophagitis": 3,
                "neurotoxicity": 4,
                "handFoot": 5,
                "skin": 5,
                "hypersensitivity": 2,
                "fatigue": 6,
                "required_doses": Decimal("3788.800093")}, {"chi": 1005549224,
                "regime_id": 2891,
                "intention_id": 1710,
                "cycle_id": 24182,
                "drug_names": "BEP 5 DAY MET",
                "diagnosis": "Breast Cancer",
                "init_appointment_date": datetime.datetime(2020, 8, 6, 0, 0),
                "elapsed_days": 0,
                "interval_days": 15,
                "appointment_date": datetime.datetime(2020, 8, 6, 0, 0),
                "intention": "Neo-Adjuvant",
                "regime": "FEC-D (D)",
                "cycle": 1,
                "p_ps": -1,
                "ps": 2,
                "nausea": 2,
                "vomiting": 3,
                "diarrhoea": 6,
                "constipation": 2,
                "oralMucositis": 3,
                "oesophagitis": 3,
                "neurotoxicity": 2,
                "handFoot": 2,
                "skin": 5,
                "hypersensitivity": 4,
                "fatigue": 4,
                "required_doses": Decimal("3338.507707")
            }, 
            {
                "chi": 1005549224,
                "regime_id": 3423,
                "intention_id": 2032,
                "cycle_id": 28527,
                "drug_names": "BEP 5 DAY MET",
                "diagnosis": "Breast Cancer",
                "init_appointment_date": datetime.datetime(2020, 12, 16, 0, 0),
                "elapsed_days": 42,
                "interval_days": 20,
                "appointment_date": datetime.datetime(2021, 1, 27, 0, 0),
                "intention": "Neo-Adjuvant",
                "regime": "PACLITAX WKLY",
                "cycle": 3,
                "p_ps": -1,
                "ps": 1,
                "vomiting": 1,
                "diarrhoea": 1,
                "constipation": 6,
                "oralMucositis": 2,
                "oesophagitis": 6,
                "neurotoxicity": 6,
                "handFoot": 1,
                "skin": 2,
                "hypersensitivity": 1,
                "fatigue": 1,
                "required_doses": Decimal("918.450870")
            }, 
            {
                "chi": 1005549224,
                "regime_id": 3421,
                "intention_id": 2030,
                "cycle_id": 28589,
                "drug_names": "CARBO&PACLI WKLY",
                "diagnosis": "Breast Cancer",
                "init_appointment_date": datetime.datetime(2020, 6, 25, 0, 0),
                "elapsed_days": 126,
                "appointment_date": datetime.datetime(2020, 10, 29, 0, 0),
                "intention": "Neo-Adjuvant",
                "regime": "PACLITAX WKLY",
                "cycle": 7,
                "p_ps": -1,
                "ps": 2,
                "nausea": 0,
                "diarrhoea": 2,
                "constipation": 3,
                "oralMucositis": 3,
                "oesophagitis": 2,
                "neurotoxicity": 3,
                "handFoot": 6,
                "skin": 3,
                "hypersensitivity": 5,
                "fatigue": 3,
                "required_doses": Decimal("2004.030147")}, {"chi": 1005549224,
                "regime_id": 3647,
                "intention_id": 2161,
                "cycle_id": 30524,
                "drug_names": "BEP 5 DAY MET",
                "diagnosis": "Breast Cancer",
                "init_appointment_date": datetime.datetime(2018, 9, 11, 0, 0),
                "elapsed_days": 0,
                "interval_days": 5,
                "appointment_date": datetime.datetime(2018, 9, 11, 0, 0),
                "intention": "Neo-Adjuvant",
                "cycle": 1,
                "p_ps": -1,
                "ps": 3,
                "nausea": 0,
                "vomiting": 1,
                "diarrhoea": 6,
                "constipation": 6,
                "oralMucositis": 3,
                "oesophagitis": 1,
                "neurotoxicity": 1,
                "handFoot": 4,
                "skin": 1,
                "hypersensitivity": 2,
                "fatigue": 1,
                "required_doses": Decimal("2037.483224")
            }, 
            {
                "chi": 1005549224,
                "regime_id": 4544,
                "intention_id": 2679,
                "cycle_id": 38255,
                "drug_names": "CAPOX",
                "diagnosis": "Breast Cancer",
                "init_appointment_date": datetime.datetime(2018, 8, 8, 0, 0),
                "elapsed_days": 147,
                "interval_days": 15,
                "appointment_date": datetime.datetime(2019, 1, 2, 0, 0),
                "intention": "Neo-Adjuvant",
                "regime": "FEC-D (D)",
                "cycle": 8,
                "p_ps": -1,
                "ps": 1,
                "nausea": 0,
                "vomiting": 0,
                "diarrhoea": 2,
                "constipation": 6,
                "oesophagitis": 2,
                "neurotoxicity": 4,
                "handFoot": 5,
                "skin": 2,
                "hypersensitivity": 4,
                "fatigue": 4,
                "required_doses": Decimal("4984.528361")}, {"chi": 1005549224,
                "regime_id": 4555,
                "intention_id": 2685,
                "cycle_id": 38391,
                "drug_names": "CARBO&PACLI WKLY",
                "diagnosis": "Breast Cancer",
                "init_appointment_date": datetime.datetime(2018, 12, 29, 0, 0),
                "elapsed_days": 147,
                "interval_days": 15,
                "appointment_date": datetime.datetime(2019, 5, 25, 0, 0),
                "intention": "Neo-Adjuvant",
                "regime": "PACLITAX WKLY",
                "cycle": 8,
                "p_ps": -1,
                "ps": 2,
                "nausea": 1,
                "vomiting": 4,
                "diarrhoea": 2,
                "constipation": 1,
                "oralMucositis": 3,
                "oesophagitis": 1,
                "neurotoxicity": 2,
                "handFoot": 6,
                "skin": 4,
                "hypersensitivity": 5,
                "fatigue": 1,
                "required_doses": Decimal("3828.312595")}, {"chi": 1005549224,
                "regime_id": 4705,
                "intention_id": 2766,
                "cycle_id": 39699,
                "drug_names": "BEP 5 DAY MET",
                "diagnosis": "Breast Cancer",
                "init_appointment_date": datetime.datetime(2020, 11, 16, 0, 0),
                "elapsed_days": 126,
                "interval_days": 15,
                "appointment_date": datetime.datetime(2021, 3, 22, 0, 0),
                "intention": "Neo-Adjuvant",
                "regime": "PACLITAX",
                "cycle": 7,
                "p_ps": -1,
                "ps": 3,
                "nausea": 0,
                "vomiting": 1,
                "diarrhoea": 5,
                "constipation": 5,
                "oralMucositis": 0,
                "oesophagitis": 3,
                "neurotoxicity": 5,
                "handFoot": 6,
                "skin": 6,
                "hypersensitivity": 6,
                "fatigue": 3,
                "required_doses": Decimal("1290.775893")}, {"chi": 1005549224,
                "regime_id": 4773,
                "intention_id": 2814,
                "cycle_id": 40280,
                "drug_names": "BEP 5 DAY MET",
                "diagnosis": "Breast Cancer",
                "init_appointment_date": datetime.datetime(2020, 4, 2, 0, 0),
                "elapsed_days": 210,
                "interval_days": 20,
                "appointment_date": datetime.datetime(2020, 10, 29, 0, 0),
                "intention": "Neo-Adjuvant",
                "regime": "DOCETAXEL BREAST",
                "cycle": 11,
                "p_ps": -1,
                "ps": 1,
                "nausea": 3,
                "vomiting": 4,
                "diarrhoea": 4,
                "constipation": 5,
                "oralMucositis": 0,
                "oesophagitis": 3,
                "neurotoxicity": 4,
                "handFoot": 4,
                "skin": 4,
                "hypersensitivity": 1,
                "fatigue": 2,
                "required_doses": Decimal("4094.768910")
            }, 
            {
                "chi": 1005549224,
                "regime_id": 4798,
                "intention_id": 2798,
                "drug_names": "CARBO&PACLI WKLY",
                "diagnosis": "Breast Cancer",
                "init_appointment_date": datetime.datetime(2021, 2, 13, 0, 0),
                "elapsed_days": 21,
                "interval_days": 15,
                "appointment_date": datetime.datetime(2021, 3, 6, 0, 0),
                "intention": "Neo-Adjuvant",
                "cycle": 2,
                "p_ps": -1,
                "ps": 2,
                "nausea": 4,
                "vomiting": 4,
                "diarrhoea": 1,
                "constipation": 1,
                "oralMucositis": 0,
                "oesophagitis": 3,
                "neurotoxicity": 3,
                "handFoot": 3,
                "skin": 1,
                "hypersensitivity": 3,
                "fatigue": 2,
                "required_doses": Decimal("1560.428292")}, {"chi": 1005549224,
                "regime_id": 5092,
                "intention_id": 3007,
                "cycle_id": 42778,
                "drug_names": "BEP 5 DAY MET",
                "diagnosis": "Breast Cancer",
                "init_appointment_date": datetime.datetime(2018, 2, 19, 0, 0),
                "elapsed_days": 63,
                "interval_days": 19,
                "appointment_date": datetime.datetime(2018, 4, 23, 0, 0),
                "intention": "Neo-Adjuvant",
                "regime": "FEC-D (D)",
                "cycle": 4,
                "p_ps": -1,
                "ps": 3,
                "nausea": 2,
                "vomiting": 2,
                "diarrhoea": 5,
                "constipation": 2,
                "oralMucositis": 3,
                "oesophagitis": 5,
                "neurotoxicity": 3,
                "handFoot": 6,
                "skin": 6,
                "fatigue": 6,
                "required_doses": Decimal("4536.198734")
            }, 
            {
                "chi": 1005549224,
                "regime_id": 5084,
                "intention_id": 3005,
                "cycle_id": 42903,
                "drug_names": "CARBO&PACLI WKLY",
                "diagnosis": "Breast Cancer",
                "init_appointment_date": datetime.datetime(2018, 4, 23, 0, 0),
                "elapsed_days": 273,
                "interval_days": 17,
                "appointment_date": datetime.datetime(2021, 1, 10, 0, 0),
                "intention": "Neo-Adjuvant",
                "regime": "DOCETAXEL BREAST",
                "cycle": 2,
                "p_ps": -1,
                "ps": 3,
                "nausea": 4,
                "vomiting": 1,
                "diarrhoea": 5,
                "constipation": 4,
                "oralMucositis": 3,
                "oesophagitis": 4,
                "neurotoxicity": 4,
                "handFoot": 1,
                "skin": 3,
                "hypersensitivity": 4,
                "fatigue": 1,
                "required_doses": Decimal("2137.767392")
            }
        ],
        "ustan.general": [
            {
                "chi": 1005549224,
                "incidence_date": datetime.datetime(2017, 4, 18, 0, 0),
                "site_icd_10": "C50.9",
                "name": "HERMIONE KOCZUR",
                "date_of_birth": datetime.datetime(1954, 5, 10, 0, 0),
                "first_seen_date": datetime.datetime(2017, 4, 18, 0, 0),
                "site": "C50.9",
                "histology": 8508,
                "primary": 1,
                "metastasis1": "C00.0",
                "metastasis2": None,
                "metastasis3": None,
                "smid": None,
                "smid1": None,
                "cong_heart_fail_flag": 0,
                "con_tiss_disease_rheum_flag": 0,
                "dementia_flag": 0,
                "pulmonary_flag": 0,
                "con_tiss_flag": 0,
                "diabetes_flag": 0,
                "para_hemiplegia_flag": 0,
                "renal_flag": 0,
                "liver_flag": 0,
                "aids_hiv_flag": 0,
                "cancer_flag": 6,
                "charlson_score": 6,
                "dob": datetime.datetime(1954, 5, 10, 0, 0),
                "age": 63,
                "simd": Decimal("5.00"),
                "simd1": Decimal("1.00"),
                "side": 2,
                "gender": 2,
                "age_at_diagnosis": Decimal("5.20"),
                "weight": Decimal("68.60"),
                "bmi": Decimal("25.50"),
                "height": Decimal("1.64"),
                "religion": 0,
                "civil_st": 9,
                "ref_hospital": 617,
                "postcode_pre": "KY",
                "postcode_suf": "953HY",
                "stage": 2,
                "stage_detail": "2A",
                "tnm_t": 1,
                "tnm_t_detail": "1",
                "tnm_n": 0,
                "tnm_n_detail": "0",
                "tnm_m": 0,
                "perf_stat": None,
                "smr01_flag": 0,
                "postcode": "KY953HY",
                "gp_name": "KIVIOJA",
                "death_flag": 0,
                "survival_days": None,
                "dat_death": None,
                "gp_id": 18
            }
        ],
        "ustan.intentions": [
            {
                "chi": 1005549224,
                "patient_id": 335,
                "intention_id": 344,
                "intention_seq": 1,
                "first_intention": "Neo-Adjuvant",
                "regime_ratio": 1,
                "cycle_ratio": 13,
                "intention": "Neo-Adjuvant",
                "first_regime": "FEC-D NEO(FEC)",
                "init_appointment_date": datetime.datetime(2020, 10, 8, 0, 0),
                "elapsed_days": 0,
                "appointment_date": datetime.datetime(2020, 10, 8, 0, 0)}],
                "ustan.patients": [{"chi": 1005549224,
                "patient_id": 335,
                "first_intention": "Neo-Adjuvant",
                "appointment_date": datetime.datetime(2020, 10, 8, 0, 0)}],
                "ustan.regimes": [{"chi": 1005549224,
                "intention_id": 670,
                "regime_id": 1151,
                "regime_seq": 298,
                "cycle_ratio": 13,
                "intention": "Neo-Adjuvant",
                "prev_regime": "EPI/CYCLO MET",
                "first_regime": "FEC-D NEO (FEC)",
                "regime": "PACLITAX",
                "interval_days": 20,
                "elapsed_days": 210,
                "init_appointment_date": datetime.datetime(2020, 10, 8, 0, 0),
                "appointment_date": datetime.datetime(2021, 5, 6, 0, 0)
            }, 
            {
                "chi": 1005549224,
                "intention_id": 2642,
                "regime_seq": 1174,
                "regime_ratio": None,
                "cycle_ratio": 13,
                "intention": "Neo-Adjuvant",
                "prev_regime": "PACLITAX",
                "first_regime": "FEC-D NEO (FEC)",
                "regime": "PACLITAX",
                "interval_days": 20,
                "elapsed_days": 420,
                "init_appointment_date": datetime.datetime(2020, 10, 8, 0, 0),
                "appointment_date": datetime.datetime(2021, 12, 2, 0, 0)}, {"chi": 1005549224,
                "intention_id": 3055,
                "regime_id": 5184,
                "regime_seq": 1342,
                "regime_ratio": None,
                "cycle_ratio": 13,
                "intention": "Neo-Adjuvant",
                "prev_regime": "FEC-D NEO (FEC)",
                "first_regime": "FEC-D NEO (FEC)",
                "regime": "DOCETAXEL",
                "interval_days": 17,
                "elapsed_days": 17,
                "init_appointment_date": datetime.datetime(2020, 10, 8, 0, 0),
                "appointment_date": datetime.datetime(2021, 5, 6, 0, 0)
            }
        ],
        "ustan.smr01": [
            {
                "chi": 1005549224,
                "incidence_date": datetime.datetime(2016, 4, 30, 0, 0),
                "admission_date": datetime.datetime(2016, 6, 2, 0, 0),
                "length_of_stay": 0,
                "other_condition1": None,
                "other_condition2": None,
                "other_condition3": None,
                "main_operation_b": "Z94.3",
                "discharge_date": datetime.datetime(2016, 6, 1, 0, 0),
                "waiting_list_type": 2,
                "main_condition": "C509",
                "main_operation_a": "X388",
                "marital_status": "Z",
                "ethnic_group": "98"}, {"chi": 1005549224,
                "incidence_date": datetime.datetime(2016, 4, 30, 0, 0),
                "admission_date": datetime.datetime(2016, 9, 16, 0, 0),
                "length_of_stay": 0,
                "other_condition1": "C773",
                "other_condition2": None,
                "other_condition3": None,
                "main_operation_b": None,
                "discharge_date": datetime.datetime(2016, 9, 15, 0, 0),
                "waiting_list_type": 2,
                "main_condition": "C509",
                "main_operation_a": "X369",
                "marital_status": "Z",
                "ethnic_group": "1B"}],
                "ustan.smr06": [{"chi": 1005549224,
                "incidence_date": datetime.datetime(2015, 3, 4, 0, 0),
                "er_status": 1,
                "her2_status": 1,
                "stage_clinical_t": "4b",
                "stage_clinical_n": "1",
                "stage_clinical_m": "X",
                "num_positive": None,
                "pathological_tum_size": None
            }
        ]
    }
}
