tags = [
  {
    "tag": "all",
    "source": "ustan.cycles",
    "fields": [
      "chi",
      "regime_id",
      "intention_id",        
      "cycle_id",
      "drug_names",
      "diagnosis",
      "init_appointment_date",
      "elapsed_days",
      "interval_days",
      "appointment_date",
      "intention",
      "regime",
      "cycle",
      "p_ps",
      "ps",
      "nausea",
      "vomiting",
      "diarrhoea",
      "constipation",
      "oralMucositis",
      "oesophagitis",
      "neurotoxicity",
      "handFoot",
      "skin",
      "hypersensitivity",
      "fatigue",
      "required_doses"
    ],
    "key_lookup": {},
    "table": True,
    "graph": False,
    "image": False
  },
  {
    "tag": "all",
    "source": "ustan.general",
    "fields": [
      "chi",
      "incidence_date",
      "site_icd_10",
      "name",
      "date_of_birth",
      "first_seen_date",
      "site",
      "histology",
      "primary",
      "metastasis1",
      "metastasis2",
      "metastasis3",
      "smid",
      "smid1",
      "cong_heart_fail_flag",
      "con_tiss_disease_rheum_flag",
      "dementia_flag",
      "pulmonary_flag",
      "con_tiss_flag",
      "diabetes_flag",
      "para_hemiplegia_flag",
      "renal_flag",
      "liver_flag",
      "aids_hiv_flag",
      "cancer_flag",
      "charlson_score",
      "dob",
      "age",
      "simd",
      "simd1",
      "side",
      "gender",
      "age_at_diagnosis",
      "weight",
      "bmi",
      "height",
      "religion",
      "civil_st",
      "ref_hospital",
      "postcode_pre",
      "postcode_suf",
      "stage",
      "stage_detail",
      "tnm_t",
      "tnm_t_detail",
      "tnm_n",
      "tnm_n_detail",
      "tnm_m",
      "perf_stat",
      "smr01_flag",
      "postcode",
      "gp_name",
      "death_flag",
      "survival_days",
      "dat_death",
      "gp_id"
    ],
    "key_lookup": {},
    "table": True,
    "graph": False,
    "image": False
  },
  {
    "tag": "all",
    "source": "ustan.intentions",
    "fields": [
      "chi",
      "patient_id",
      "intention_id",
      "intention_seq",
      "first_intention",
      "regime_ratio",
      "cycle_ratio",
      "intention",
      "first_regime",
      "init_appointment_date",
      "elapsed_days",
      "appointment_date"
    ],
    "key_lookup": {},
    "table": True,
    "graph": False,
    "image": False
  },
  {
    "tag": "all",
    "source": "ustan.patients",
    "fields": [
      "chi",
      "patient_id",
      "first_intention",
      "appointment_date"
    ],
    "key_lookup": {},
    "table": True,
    "graph": False,
    "image": False
  },
  {
    "tag": "all",
    "source": "ustan.regimes",
    "fields": [
      "chi",
      "intention_id",
      "regime_id",
      "regime_seq",
      "regime_ratio",
      "cycle_ratio",
      "intention",
      "prev_regime",
      "first_regime",
      "regime",
      "interval_days",
      "elapsed_days",
      "init_appointment_date",
      "appointment_date"
    ],
    "key_lookup": {},
    "table": True,
    "graph": False,
    "image": False
  },
  {
    "tag": "all",
    "source": "ustan.smr01",
    "fields": [
      "chi",
      "incidence_date",
      "admission_date",
      "length_of_stay",
      "other_condition1",
      "other_condition2",
      "other_condition3",
      "main_operation_b",
      "discharge_date",
      "waiting_list_type",
      "main_condition",
      "main_operation_a",
      "marital_status",
      "ethnic_group"
    ],
    "key_lookup": {},
    "table": True,
    "graph": False,
    "image": False
  },
  {
    "tag": "all",
    "source": "ustan.smr06",
    "fields": [
      "chi",
      "incidence_date",
      "er_status",
      "her2_status",
      "stage_clinical_t",
      "stage_clinical_n",
      "stage_clinical_m",
      "num_positive",
      "pathological_tum_size"
    ],
    "key_lookup": {},
    "table": True,
    "graph": False,
    "image": False
  }
]